=== Nopezal/PoroCYon.MCT/Mod Creation Tools/Schemas/ModInfoSchema.json
{
    "id": "https://dl.dropboxusercontent.com/u/151130168/MCT/Schemas/ModInfoSchema.json",
    "$schema": "http://json-schema.org/draft-04/schema#",
    "type": "object",
    "description": "schema for a ModInfo.json file",
    
    "properties": {
        "internalName": {
            "type": "string"
        },
        "displayName": {
            "type": "string"
        },

        "author": {
            "type": "string"
        },
        "info": {
            "type": "string"
        },

        "version": {
            "type": {
                "enum": [
                    "string",
                    "array"
                ]
            }
        },

        "includePDB": {
            "type": "boolean"
        },
        "warnOnReload": {
            "type": "boolean"
        },

        "modReferences": {
            "type": "array",
            "oneOf": [
                "string"
            ]
        },
        "dllReferences": {
            "type": "array",
            "oneOf": [
                "string"
            ]
        },

        "MSBuild": {
            "type": "boolean"
        },
        "msBuildFile": {
            "type": "string"
        }
    },

    "additionalProperties": false,
    "required": [
        "internalName",
        "displayName"
    ]
}

=== Nopezal/PoroCYon.MCT/Empty tAPI Mod/ModInfo.json
{
    "displayName": "$projectname$",
    "author": "$registeredorganization$",
    "version": "0.0.0.0",
    "info": "$projectname$ by $registeredorganization$ v0.0.0.0",
    
    "internalName": "$safeprojectname$",

    "MSBuild": true,
    "msBuildFile": "$(ProjectPath)",

    "includePDB": true
}

=== Nopezal/PoroCYon.MCT/Mod Creation Tools/ModInfo.json
{
	"displayName": "Mod Creation Tools",
	"author": "PoroCYon",
	"version": "1.0.0.0",
	"info": "PoroCYon's Mod Creation Tools\n\nDo not change the state of this mod.\nIt's automatically turned on when a mod needs it,\nand turned off otherwise.",
    
	"internalName": "PoroCYon.MCT",

    "MSBuild": true,

    "includePDB": true
}

=== Nopezal/PoroCYon.MCT/MCT Mod placeholder/ModInfo.json
{
    "$schema": "https://dl.dropboxusercontent.com/u/151130168/MCT/Schemas/ModInfoSchema.json",

    "displayName": "Mod Creation Tools",
    "author": "PoroCYon",
    "version": "1.1.0.6",
    "info": "PoroCYon's Mod Creation Tools\n\nDo not change the state of this mod.\nIt's automatically turned on when a mod needs it,\nand turned off otherwise.",
    
    "internalName": "PoroCYon.MCT",

    "MSBuild": true,
    "msBuildFile": "MCT Mod placeholder.csproj",

    "includePDB": true
}
